// Package clients provides client management functionality for the GoBroke system.
package clients

import "github.com/google/uuid"

// clientOptsFunc is a function type that modifies clientOpts.
// It's used to implement the functional options pattern for client configuration.
type clientOptsFunc func(*clientOpts)

// clientOpts holds configuration options for client creation.
type clientOpts struct {
	uuid string // Unique identifier for the client
}

// defaultOpts returns a clientOpts with default values.
// It generates a new random UUID for the client.
func defaultOpts() clientOpts {
	return clientOpts{
		uuid: uuid.New().String(),
	}
}

// WithUUID returns a clientOptsFunc that sets a custom UUID for a client.
// If not used, a new random UUID will be generated by default.
func WithUUID(uuid string) clientOptsFunc {
	return func(opts *clientOpts) {
		opts.uuid = uuid
	}
}
