// Package clients provides client management functionality for the GoBroke system.
package clients

import "github.com/google/uuid"

// Option configures a client. Pass options to New.
type Option func(*clientOpts)

// clientOpts holds configuration options for client creation.
type clientOpts struct {
	uuid string // Unique identifier for the client
}

// defaultOpts returns a clientOpts with default values.
// It generates a new random UUID for the client.
func defaultOpts() clientOpts {
	return clientOpts{
		uuid: uuid.New().String(),
	}
}

// WithUUID returns an Option that sets a custom UUID for a client.
// If not used, a new random UUID will be generated by default.
func WithUUID(uuid string) Option {
	return func(opts *clientOpts) {
		opts.uuid = uuid
	}
}
