// Package message provides message creation and configuration options.
package message

import (
	"github.com/google/uuid"
)

// messageOptsFunc is a function type that modifies messageOpts.
// It's used to implement the functional options pattern for message configuration.
type messageOptsFunc func(*messageOpts)

// messageOpts holds configuration options for message creation.
type messageOpts struct {
	metadata map[string]any
	uuid     string
}

// defaultOpts returns a messageOpts with default values.
// It initializes a new UUID and sets metadata to nil.
func defaultOpts() messageOpts {
	return messageOpts{
		metadata: nil,
		uuid:     uuid.New().String(),
	}
}

// WithMetadata returns a messageOptsFunc that sets custom metadata for a message.
// The metadata can be any key-value pairs that should be associated with the message.
func WithMetadata(metadata map[string]any) messageOptsFunc {
	return func(opts *messageOpts) {
		opts.metadata = metadata
	}
}

// WithUUID returns a messageOptsFunc that sets a custom UUID for a message.
// If not used, a new random UUID will be generated by default.
func WithUUID(uuid string) messageOptsFunc {
	return func(opts *messageOpts) {
		opts.uuid = uuid
	}
}
