package message

import (
	"testing"

	"github.com/A13xB0/GoBroke/clients"
	"github.com/A13xB0/GoBroke/types"
)

func TestConstructors(t *testing.T) {
	from, to := clients.New(), clients.New()
	meta := map[string]any{"k": 1}
	cases := []struct {
		name string
		m    types.Message
	}{
		{"client", NewClientMessage(from, []*clients.Client{to}, []types.LogicName{"l"}, []byte("x"), WithMetadata(meta), WithUUID("id"))},
		{"simpleClient", NewSimpleClientMessage(from, to, "l", []byte("x"), WithMetadata(meta), WithUUID("id"))},
		{"logic", NewLogicMessage("src", []*clients.Client{to}, []types.LogicName{"l"}, []byte("x"), WithMetadata(meta), WithUUID("id"))},
		{"simpleLogic", NewSimpleLogicMessage("src", to, "l", []byte("x"), WithMetadata(meta), WithUUID("id"))},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if c.m.UUID != "id" || c.m.Metadata["k"] != 1 || string(c.m.MessageRaw) != "x" {
				t.Fatalf("options not applied: %+v", c.m)
			}
			if len(c.m.ToClient) != 1 || c.m.ToClient[0] != to || len(c.m.ToLogic) != 1 || c.m.ToLogic[0] != "l" {
				t.Fatalf("routing not set: %+v", c.m)
			}
			if c.m.Tags == nil {
				t.Fatal("Tags should be allocated")
			}
		})
	}
	if NewClientMessage(from, nil, nil, nil).FromClient != from {
		t.Fatal("FromClient not set")
	}
	if NewLogicMessage("src", nil, nil, nil).FromLogic != "src" {
		t.Fatal("FromLogic not set")
	}
	if NewLogicMessage("src", nil, nil, nil).UUID == "" {
		t.Fatal("a UUID should be generated by default")
	}
}
